#
# Module manifest for module "PowerTools"
#
# Generated by: Stefan Greve
#
# Generated on: 11/25/2024
#
# NOTE: The values below are populated by scripts/build.ps1, which rewrites this file in full, so
# manual edits do not survive a build. Release metadata is pinned in scripts/publish.ps1.
#

@{
    RootModule = "PowerTools.psm1"
    ModuleVersion = "2.0.0"
    GUID = "84f794f0-1d55-46d8-b1d8-dc589335f49a"
    Author = ""
    CompanyName = ""
    Copyright = ""
    Description = ""
    PowerShellVersion = "7.4"
    FunctionsToExport = @()
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
    FileList = @()
    RequiredModules = @()
    ScriptsToProcess = @()
    TypesToProcess = @()
    FormatsToProcess = @()
    PrivateData = @{
        PSData = @{}
    }
}
