#
# Module manifest for module "PowerTools"
#
# Generated by: Stefan Greve
#
# Generated on: 11/25/2024
#

@{
    RootModule = "PowerTools.psm1"
    ModuleVersion = "2.0.0"
    GUID = "84f794f0-1d55-46d8-b1d8-dc589335f49a"
    Author = "Stefan Greve"
    CompanyName = "Advanced Systems"
    Copyright = "(c) 2024 Advanced Systems. All rights reserved."
    Description = "General purpose Cmdlets for all platforms."
    PowerShellVersion = "7.4"
    FunctionsToExport = @()
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
    FileList = @()
    RequiredModules = @()
    ScriptsToProcess = @()
    TypesToProcess = @()
    FormatsToProcess = @()
    PrivateData = @{
        PSData = @{
            Tags = @("PSEdition_Core", "Windows", "MacOS", "Linux")
            IconUri = "https://raw.githubusercontent.com/Advanced-Systems/assets/refs/heads/master/logos/png/adv-logo_85x85.png"
            LicenseUri = "https://github.com/StefanGreve/profile/blob/master/LICENSE.md"
            ProjectUri = "https://github.com/StefanGreve/profile"
            ReleaseNotes = "https://github.com/StefanGreve/profile/blob/master/CHANGELOG.md"
        }
    }
}
