name: Unit Test
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Unit Tests
        shell: pwsh
        run: ./scripts/test.ps1 -Build -Version 0.0.0
