name: Unit Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        shell: pwsh
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer

      - name: Run Unit Tests
        shell: pwsh
        run: |
          pwsh -NoProfile -ExecutionPolicy ByPass -File ./scripts/test.ps1 -Build


